name: Continuous Integration
on:
  pull_request:
    branches: [dev]
jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm cypress
      - run: npm run build