name: Continuous Integration
on:
  pull_request:
    branches: [dev]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm start
